// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"leke/internal/dao/internal"
)

// departmentDao is the data access object for the table department.
// You can define custom methods on it to extend its functionality as needed.
type departmentDao struct {
	*internal.DepartmentDao
}

var (
	// Department is a globally accessible object for table department operations.
	Department = departmentDao{internal.NewDepartmentDao()}
)

// Add your custom methods and functionality below.
