// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"leke/internal/dao/internal"
)

// fansDao is the data access object for the table fans.
// You can define custom methods on it to extend its functionality as needed.
type fansDao struct {
	*internal.FansDao
}

var (
	// Fans is a globally accessible object for table fans operations.
	Fans = fansDao{internal.NewFansDao()}
)

// Add your custom methods and functionality below.
