// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"leke/internal/dao/internal"
)

// subscribeDao is the data access object for the table subscribe.
// You can define custom methods on it to extend its functionality as needed.
type subscribeDao struct {
	*internal.SubscribeDao
}

var (
	// Subscribe is a globally accessible object for table subscribe operations.
	Subscribe = subscribeDao{internal.NewSubscribeDao()}
)

// Add your custom methods and functionality below.
