// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"leke/internal/dao/internal"
)

// userDepartmentDao is the data access object for the table user_department.
// You can define custom methods on it to extend its functionality as needed.
type userDepartmentDao struct {
	*internal.UserDepartmentDao
}

var (
	// UserDepartment is a globally accessible object for table user_department operations.
	UserDepartment = userDepartmentDao{internal.NewUserDepartmentDao()}
)

// Add your custom methods and functionality below.
